spring.application.name=user-service

# Config Server
spring.config.import=optional:configserver:http://config-server:8888
spring.cloud.config.fail-fast=false

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Zipkin / Tracing
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized

# OpenAPI
springdoc.swagger-ui.enabled=true

logging.level.root=INFO
logging.level.by.bntu.salaryapp=DEBUG
logging.level.org.springframework.security=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n

# Admin / Superuser initialization
app.admin.username=admin
app.admin.email=admin@salary-app.local
app.admin.password=./doc
app.admin.firstName=Super
app.admin.lastName=User
app.admin.surname=Administrator

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

spring.datasource.url=jdbc:postgresql://postgres:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=2580
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect