spring.application.name=salary-app

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.enabled=true

token.signing.key=${TOKEN_SIGNING_KEY}

spring.jpa.hibernate.ddl-auto=create-drop
spring.liquibase.enabled=false
spring.jpa.show-sql=false

logging.level.root=INFO
logging.level.by.bntu.salaryapp=DEBUG
logging.level.org.springframework.security=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n
