apiVersion: v1
kind: ConfigMap
metadata:
  name: salary-app-config
  namespace: default
data:
  JWT_SIGNING_KEY: "mySecretKey"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "2580"
  SPRING_PROFILES_ACTIVE: "k8s"