spring:
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    gateway:
      filter:
        weight-calculator:
          enabled: false
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:3000
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: true
            exposedHeaders:
              - Authorization
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

token:
  signing:
    key: ${TOKEN_SIGNING_KEY:wQrd5gfnUzAHa9Woqf3KgkI5r0VYFhv5u2ZpFjS6m7U=}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

server:
  port: 8080