spring:
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    gateway:
      filter:
        weight-calculator:
          enabled: false
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users,/api/users/**
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/employees,/api/employees/**
          filters:
            - JwtAuthenticationFilter
        - id: position-service
          uri: lb://employee-service
          predicates:
            - Path=/api/positions,/api/positions/**
          filters:
            - JwtAuthenticationFilter
        - id: qualification-service
          uri: lb://employee-service
          predicates:
            - Path=/api/qualifications,/api/qualifications/**
          filters:
            - JwtAuthenticationFilter
        - id: subject-service
          uri: lb://employee-service
          predicates:
            - Path=/api/subjects,/api/subjects/**
          filters:
            - JwtAuthenticationFilter
        - id: experience-service
          uri: lb://employee-service
          predicates:
            - Path=/api/experiences,/api/experiences/**
          filters:
            - JwtAuthenticationFilter
        - id: datatable-service
          uri: lb://datatable-service
          predicates:
            - Path=/api/datatables,/api/datatables/**
          filters:
            - JwtAuthenticationFilter
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:3000
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: true
            exposedHeaders:
              - Authorization
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

token:
  signing:
    key: ${TOKEN_SIGNING_KEY:wQrd5gfnUzAHa9Woqf3KgkI5r0VYFhv5u2ZpFjS6m7U=}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

server:
  port: 8080
