spring.application.name=employee-service

spring.datasource.url=jdbc:postgresql://postgres:5432/employee_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:2580}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.enabled=true

logging.level.root=INFO
logging.level.by.bntu.salaryapp=DEBUG

server.port=8083

# Config Server
spring.config.import=optional:configserver:http://config-server:8888
spring.cloud.config.fail-fast=false
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
# Zipkin / Tracing
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

